### ISSUE TITLE
🇺🇳 [LANGUAGE] - Polish translation

### ISSUE THREAD

**Issue by Mittelblut9** [Mittelbots/Mittelbot#1212]
### Description

- translate the bot to polish

**Comment by Neyviin** [comment]
hello world

**Comment by Mittelblut9** [comment]
Blocked by #1250

**Comment by Mittelblut9** [comment]
Ready for action 👍

**Comment by Mittelblut9** [comment]
@Neyviin I have changed the translation feature to Crowdin. 
You can now translate the polish texts at https://translate.mittelbot.xyz

**Comment by Mittelblut9** [comment]
Done
