### ISSUE TITLE
🐛 [BUG] - Bot is not starting correctly

### ISSUE THREAD

**Issue by NICK-FURY-6023** [Mittelbots/Mittelbot#1769]
### Description

Bot can't run 

And you don't have support server link 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

**Comment by Mittelblut9** [comment]
Hello, i have a support server. You can click on the Button at the read me.

**Comment by Mittelblut9** [comment]
Note: It's an know issue with an workaround. See Readme.md.
