### ISSUE TITLE
🐛 [BUG] - Cannot find module 'config.json'

### ISSUE THREAD

**Issue by sysserv** [Mittelbots/Mittelbot#1795]
### Description

Despite adding 'resolveJsonModule': true to the jsconfig.json file, the error persists. Modifying the directory path also failed to resolve the issue. 

(Note: The screenshot of error path of the config file was changed for testing purposes)

### Reproduction steps

```bash
~assets/json/_config/config.json
```

### Screenshots

<img width="550" alt="Screenshot 2023-11-26 at 2 29 06 PM" src="https://github.com/Mittelbots/Mittelbot/assets/13867687/1948c430-bd67-491f-afee-6ba2e932651c">

**Comment by Mittelblut9** [comment]
Execute the following command depending on your OS

```bash
# Linux
bash ./scripts/install-linux.sh

# Windows
./scripts/install-windows.bat

```

https://github.com/Mittelbots/Mittelbot?tab=readme-ov-file#known-issues

**Comment by sysserv** [comment]
> Execute the following command depending on your OS
> 
> ```shell
> # Linux
> bash ./scripts/install-linux.sh
> 
> # Windows
> ./scripts/install-windows.bat
> ```
> 
> https://github.com/Mittelbots/Mittelbot?tab=readme-ov-file#known-issues


Already tested it, same error, despite thorough testing. I'm using macOS, Visual Studio Code, and Docker.

**Comment by Mittelblut9** [comment]
Delete the node_modules folder, run `npm i` outside of the docker container and start the containers. 
The current docker setup is kinda scuffed, haven't improved it yet. 

If it's still there run the linux command again. Maybe that will help.

Else i have to reproduce the bug 🤔

**Comment by sysserv** [comment]
> Delete the node_modules folder, run `npm i` outside of the docker container and start the containers. The current docker setup is kinda scuffed, haven't improved it yet.
> 
> If it's still there run the linux command again. Maybe that will help.
> 
> Else i have to reproduce the bug 🤔

I will thoroughly investigate this issue by conducting additional testing. I will promptly inform you of any progress or resolution.

**Comment by sysserv** [comment]
Due to macOS's System Integrity Protection (SIP), which is always enabled by default, it is necessary to employ the 'sudo' command to execute commands with administrative privileges. To address this requirement, I modified the 'install-linux.sh' script by incorporating the 'sudo' command to ensure proper execution.

```
#!/bin/bash

DEPLOYMENT=$1

stopContainer() {
    echo "Stopping docker container"
    docker compose down
}

startBot() {
    echo "Starting bot"
    npm run start
}

startContainer() {
    echo "Starting docker container"
    docker compose up -d
}

installNpmPackages() {
    echo "Installing npm packages in docker container"
    sudo docker compose exec ${DOCKER_CONTAINER} npm install
}

installAliasModules() {
    echo "Installing alias modules in docker container"
    sudo docker compose exec ${DOCKER_CONTAINER} npm run alias-build
}

echo "Starting installation"

DOCKER_CONTAINER="bot"

if [ "$DEPLOYMENT" != "deployment" ]; then
    answer=""
    read -e -i "$answer" -p "Do you have inserted all important data to the .env file? [y/n]: " input
    answer="${input:-$answer}"

    if [ "$answer" != "${answer#[Nn]}" ] ;then
        echo "Please insert all important data to the .env file and run the script again."
        exit 1
    fi
fi


stopContainer
startContainer
installNpmPackages
installAliasModules
stopContainer
startBot

```

**Comment by Mittelblut9** [comment]
You have probably something misconfigured. It should work even without sudo

**Comment by sysserv** [comment]
> You have probably something misconfigured. It should work even without sudo

Everything configured perfecto, told you when used sudo worked, I'm using M3 Chip

**Comment by Mittelblut9** [comment]
Everything works with sudo. But it should work without sudo too.
